@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package io.github.kawaiicakes.sleepingaround;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;